### ISSUE TITLE
Rendering problems

### ISSUE THREAD

**Issue by Ithronyar** [Hennamann/Mist-Biomes#1]
Minecraft version: 1.12.2
Forge version: 14.23.2.2611
Mist Core version: 1.2.1-1
Mist Biomes version: 1.0.0

These might be problems with Mist Core, but since I'm testing its implementation in Mist Biomes, I'm posting this here.

**Bug:** When entering a mist biome with fast graphics enabled, the world goes black. Default biomes look normal. Looks like a shader problem.
![2018-02-26_13 30 45](https://user-images.githubusercontent.com/26017430/36697030-afc792ec-1afa-11e8-8536-f6a6a891fab4.png)

**Issue:** Back to fancy graphics. The mist effect looks like a glitchy solid plane instead of fog. No matter how I configure the density, it never looks quite right.
![2018-02-26_13 45 36](https://user-images.githubusercontent.com/26017430/36697259-656cf9f2-1afb-11e8-8830-ce0e00f738a6.png)

**Comment by Hennamann** [comment]
Are you using optifine or a shader mod? As I'm aware of optifine/shaders causing issues, but I'm rather limited in terms of fixing issues relating to it due to optifines changes to the render system...

**Comment by Ithronyar** [comment]
Nope, I tested it in a completely standalone environment, with only Mist Core and Mist Biomes enabled.

**Comment by NotAVerb** [comment]
I too am having this problem.
This is a fresh world with nothing but Mist biomes and core installed.

Forge 2611
![2018-02-27_06 52 24](https://user-images.githubusercontent.com/30223331/36727319-b5715e3e-1bb4-11e8-92c6-30368f8711f3.png)

**Comment by Hennamann** [comment]
Interesting, I'll have to do some tests locally and see what's causing this to happen.

**Comment by Hennamann** [comment]
Sorry about getting back to this so late, but it turned out being a real hassle to figure out. I've partially rewritten the render code for the mist to hopefully fix the issue, you will only need to update mist core, but I'm posting the latest build of mist biomes as well:

**Mist Core**: https://maven.henrikstabell.com/com/henrikstabell/mistcore/MistCore-1.12/1.2.2-28/MistCore-1.12-1.2.2-28-universal.jar

**Mist Biomes**: https://maven.henrikstabell.com/com/henrikstabell/mistbiomes/MistBiomes-1.12/1.0.2-13/MistBiomes-1.12-1.0.2-13-universal.jar

I'm closing this for now, but let me know if the issue still persists and I'll reopen it and have another look at it.

**Comment by ProsperCraft** [comment]
Would you please push this update to Curse?  We have this same issue on the current Curse version.

**Comment by hex3f** [comment]
Link is dead! We need brand new download links! Please!
